import type {PlaneAPI} from '../../src/lib/api.js'

export function mockAPI(partial: Partial<PlaneAPI> = {}): PlaneAPI {
  return {
    async addIssuesToCycle() {},
    async addIssuesToModule() {},
    archiveCycle: async () => ({archived: true, created_at: '', id: '', name: '', project_id: '', updated_at: '', workspace_id: ''}),
    archiveModule: async () => ({archived: true, created_at: '', id: '', name: '', project_id: '', updated_at: '', workspace_id: ''}),
    createCycle: async () => ({archived: false, created_at: '', id: '', name: '', project_id: '', updated_at: '', workspace_id: ''}),
    createInitiative: async () => ({created_at: '', id: '', name: '', updated_at: '', workspace_id: ''}),
    createIntake: async () => ({created_at: '', id: '', name: '', project_id: '', status: '', updated_at: '', workspace_id: ''}),
    createIssue: async () => ({assignees: [], created_at: '', id: '', labels: [], name: '', priority: 'medium', project_id: '', sequence_id: 0, state: '', state_id: '', updated_at: '', workspace_id: ''}),
    createLabel: async () => ({color: '', created_at: '', id: '', name: '', project_id: '', updated_at: '', workspace_id: ''}),
    createModule: async () => ({archived: false, created_at: '', id: '', name: '', project_id: '', updated_at: '', workspace_id: ''}),
    createProject: async () => ({created_at: '', id: '', identifier: '', name: '', network: 1, updated_at: '', workspace: ''}),
    createProjectPage: async () => ({created_at: '', id: '', name: '', owned_by: '', project_id: '', updated_at: '', workspace_id: ''}),
    createState: async () => ({color: '', created_at: '', default: false, group: '', id: '', name: '', project_id: '', sequence: 0, updated_at: '', workspace_id: ''}),
    createWorkspacePage: async () => ({created_at: '', id: '', name: '', owned_by: '', updated_at: '', workspace_id: ''}),
    async deleteCycle() {},
    async deleteInitiative() {},
    async deleteIntake() {},
    async deleteIssue() {},
    async deleteLabel() {},
    async deleteModule() {},
    async deleteProject() {},
    async deleteState() {},
    getCurrentUser: async () => ({created_at: '', email: '', id: '', updated_at: ''}),
    getCycle: async () => ({archived: false, created_at: '', id: '', name: '', project_id: '', updated_at: '', workspace_id: ''}),
    getIssue: async () => ({assignees: [], created_at: '', id: '', labels: [], name: '', priority: 'medium', project_id: '', sequence_id: 0, state: '', state_id: '', updated_at: '', workspace_id: ''}),
    getModule: async () => ({archived: false, created_at: '', id: '', name: '', project_id: '', updated_at: '', workspace_id: ''}),
    getProject: async () => ({created_at: '', id: '', identifier: '', name: '', network: 1, updated_at: '', workspace: ''}),
    getProjectPage: async () => ({created_at: '', id: '', name: '', owned_by: '', project_id: '', updated_at: '', workspace_id: ''}),
    getWorkspacePage: async () => ({created_at: '', id: '', name: '', owned_by: '', updated_at: '', workspace_id: ''}),
    listCycles: async () => ({count: 0, results: []}),
    listInitiatives: async () => ({count: 0, results: []}),
    listIntake: async () => ({count: 0, results: []}),
    listIssues: async () => ({count: 0, results: []}),
    listLabels: async () => ({count: 0, results: []}),
    listModules: async () => ({count: 0, results: []}),
    listProjectMembers: async () => [],
    listProjects: async () => ({count: 0, results: []}),
    listStates: async () => ({count: 0, results: []}),
    listWorkspaceMembers: async () => ({count: 0, results: []}),
    async removeIssueFromCycle() {},
    async removeIssueFromModule() {},
    searchIssues: async () => [],
    async transferCycleIssues() {},
    unarchiveCycle: async () => ({archived: false, created_at: '', id: '', name: '', project_id: '', updated_at: '', workspace_id: ''}),
    unarchiveModule: async () => ({archived: false, created_at: '', id: '', name: '', project_id: '', updated_at: '', workspace_id: ''}),
    updateCycle: async () => ({archived: false, created_at: '', id: '', name: '', project_id: '', updated_at: '', workspace_id: ''}),
    updateIssue: async () => ({assignees: [], created_at: '', id: '', labels: [], name: '', priority: 'medium', project_id: '', sequence_id: 0, state: '', state_id: '', updated_at: '', workspace_id: ''}),
    updateLabel: async () => ({color: '', created_at: '', id: '', name: '', project_id: '', updated_at: '', workspace_id: ''}),
    updateModule: async () => ({archived: false, created_at: '', id: '', name: '', project_id: '', updated_at: '', workspace_id: ''}),
    updateProject: async () => ({created_at: '', id: '', identifier: '', name: '', network: 1, updated_at: '', workspace: ''}),
    ...partial,
  } as PlaneAPI
}
